leek:
  biz_dir: data            # 数据存储目录
  download_dir: download   # 下载数据目录
  alert_type: console      # 通知方式
  alert_token: xxx         # 通知token
  allowed_domains:         # web允许访问的域名
    - "*"
  position:
    min_rate: "0.05"       # 最小下单仓位
    rolling_position: true # 是否滚动仓位
  backtest:
    emulation: false       # 回测数据仿真，开启后会使用小级别数据穿插在K线中
    emulation_interval: 1m # 仿真填充K线
    target_interval: 4h    # 需仿真K线
  data_db:
    type: sqlite           # sqlite sqlite/clickhouse
    path: data/data.db     # sqlite文件位置
    database: default      # clickhouse数据库名
    host: localhost        # clickhouse host
    port: 9000             # clickhouse port
    user: default          # clickhouse user
    password:              # database password, default empty.
